on: [push]

name: AzureLoginSample

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: 'Docker build and push'
      uses: azure/docker-login@v1
      with:
        login-server: actiontest.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t actiontest.azurecr.io/nodejssampleapp:${{ github.sha }}
        docker push actiontest.azurecr.io/nodejssampleapp:${{ github.sha }}
    - name: 'Deploy to Azure Container Instances'
      uses: mitsha-microsoft/aci-create-action@v1
      with:
        resource-group: actiontest
        dns-name-label: actiontest01
        image: actiontest.azurecr.io/nodejssampleapp:${{ github.sha }}
        server: actiontest.azurecr.io
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: acitest
        location: 'west us'
